const words = [
  {
    id: "1",
    english: "cat",
    transcription: "[kæt]",
    russian: "кошка",
    tags: "",
    tags_json: "[]",
    img: "1.jpg",
  },
  {
    id: "2",
    english: "dog",
    transcription: "[dɒg]",
    russian: "собака",
    tags: "",
    tags_json: "[]",
    img: "2.jpg",
  },
  {
    id: "3",
    english: "orange",
    transcription: "[ɔːrɪndʒ]",
    russian: "апельсин",
    tags: "",
    tags_json: "[]",
    img: "3.jpg",
  },
  {
    id: "4",
    english: "sea",
    transcription: "[siː]",
    russian: "море",
    tags: "",
    tags_json: "[]",
    img: "4.jpg",
  },
  {
    id: "5",
    english: "money",
    transcription: "[ˈmʌnɪ]",
    russian: "деньги",
    tags: "",
    tags_json: "[]",
    img: "5.jpg",
  },
  {
    id: "6",
    english: "apple",
    transcription: "[æpl]",
    russian: "яблоко",
    tags: "",
    tags_json: "[]",
    img: "6.jpg",
  },
  {
    id: "7",
    english: "flower",
    transcription: "[ˈflaʊə]",
    russian: "цветок",
    tags: "",
    tags_json: "[]",
    img: "7.jpg",
  },
  {
    id: "8",
    english: "car",
    transcription: "[kɑː]",
    russian: "машина",
    tags: "",
    tags_json: "[]",
    img: "8.jpg",
  },
  {
    id: "9",
    english: "mirror",
    transcription: "[ˈmɪrə]",
    russian: "зеркало",
    tags: "",
    tags_json: "[]",
    img: "9.jpg",
  },
  {
    id: "10",
    english: "house",
    transcription: "[haʊs]",
    russian: "дом",
    tags: "",
    tags_json: "[]",
    img: "10.jpg",
  },
];

export default words;
